### PR TITLE
Rename Padding -> Margin.

### PR DESCRIPTION
**Pull request by colinrtwhite**
Also renames `start`/`end` -> `left`/`right`. Left/right fits better with the flexbox spec and we don't support right-to-left layouts.

Follow up from the conversation here: https://github.com/cashapp/redwood/issues/855

### CODE REVIEW

**Review by swankjesse — APPROVED** [review]

**Comment by veyndan** [comment]
> Also renames `start`/`end` -> `left`/`right`. Left/right fits better with the flexbox spec and we don't support right-to-left layouts.

Have you got a link to the spec? I'm kinda surprised because CSS logical properties are promoted pretty heavily (e.g., `flex-start`).

**Comment by colinrtwhite** [comment]
@veyndan Margin isn't really part of the flexbox spec so it uses the default CSS `left`/`right` names for margin: https://www.w3schools.com/css/css_margin.asp

**Comment by veyndan** [comment]
True, `flex-start` was a bad/wrong example. Margin's logical property counterparts to `margin-left`/`margin-right` are [`margin-inline-start`/`margin-inline-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline). I'm just a bit concerned going with `left`/`right` as it's exclusionary of RTL (and vertical) writing modes.

**Comment by JakeWharton** [comment]
It does seem very weird to not use start/end in anything newly built.

**Comment by colinrtwhite** [comment]
@veyndan That's a good point. I figured that using `left`/`right` was more in-line with web, but that seems incorrect. I'll revert back to `start`/`end`.

**Pull request merged**
