### PR TITLE
Disable system UI in redwood-layout screenshot tests.

### PR DESCRIPTION
**Pull request by colinrtwhite**

### CODE REVIEW

**Review by veyndan — APPROVED** [review]

**Review by JakeWharton — APPROVED** [review]
No preference here either way. In the other test the layout was appearing behind the system UI. Here it correctly appears within it making the need to disable much lower. But I'm of the opinion system UI with paparazzi should be opt-in so certainly don't mind it being removed.

**Comment by veyndan** [comment]
Should this PR be targeting `trunk`?

**Comment by JakeWharton** [comment]
It was stacked, but it maybe worth rebasing since the base one seems like it needs more work?

**Comment by colinrtwhite** [comment]
Yep, this needs to be retargeted from the base branch.

**Comment by chrisbanes** [comment]
Rebased onto trunk.

**Comment by JakeWharton** [comment]
CI didn't kick before for some reason

**Pull request merged**
