### PR TITLE
Create Redwood build plugin

### PR DESCRIPTION
**Pull request by JakeWharton**
It's like convention plugins, but better because it's an actual API that can be stateful.

### CODE REVIEW

**Review by veyndan — APPROVED** [review]
Cool

**Review by chrisbanes — APPROVED** [review]
nicceeeee

**Review by colinrtwhite — APPROVED** [review]

**Comment by JakeWharton** [comment]
Going to quickly re-enable merge commits once this goes green because each commit builds on its own.

**Comment by JakeWharton** [comment]
Also happy to finally delete my _many_ branches which have tried and failed to set this up in the past
```
$ branch | egrep 'plugin|convention'
* jw.build-plugin.2023-05-09
  jw.convention.2023-04-19
  jw/convention-plugins/2022-10-10
  jw/more-plugins/2022-09-17
  jw/build-plugin/2022-08-26
```

**Pull request merged**
