### PR TITLE
Use Apple silicon images on CI.

### PR DESCRIPTION
**Pull request by colinrtwhite**
[Released today](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/): speeds up test time by ~50% in my tests

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]

**Comment by JakeWharton** [comment]
I wonder if renovate will bump this to 15 when that inevitably comes out...

**Comment by colinrtwhite** [comment]
I don't think so, unfortunately. Though we can change it back to `macos-latest` in a few months once "latest" starts pointing to MacOS 14.

**Comment by colinrtwhite** [comment]
Blocked by: https://github.com/ReactiveCircus/android-emulator-runner/issues/350

**Comment by JakeWharton** [comment]
Emulators are now running on Linux. Please rebase (to get that change) and try again!

**Comment by colinrtwhite** [comment]
Going to close this out and maybe take another run at this in the future.

**Pull request closed without merging**
