### PR TITLE
Try out macos-latest-xl GHA runners

### PR DESCRIPTION
**Pull request by chrisbanes**
https://github.blog/changelog/2023-04-24-github-actions-faster-macos-runners-are-now-available-in-open-public-beta/

Just trying to compare the difference in time a complete run takes vs the `macos-latest` runners.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Does this invalidate the cache? Probably need a few runs to get a set of good timings.

We should add Gradle buildscan publishing for CI like SQLDelight did.

**Comment by chrisbanes** [comment]
> Does this invalidate the cache? Probably need a few runs to get a set of good timings.

Yeah, I guess it uses the runner type in the cache-key, which is a bit annoying here as they're compatible.

> We should add Gradle buildscan publishing for CI like SQLDelight did.

#978

**Comment by JakeWharton** [comment]
Well that one shard was fast!

**Comment by chrisbanes** [comment]
20% of the time, it works every time.

**Comment by chrisbanes** [comment]
Doesn't look like we have access to the XL runners for some reason. Going to close for this now.

**Pull request closed without merging**
