### PR TITLE
Revert "Update kotlinx-coroutines to v1.7.0 (#1025)"

### PR DESCRIPTION
**Pull request by swankjesse**
This reverts commit c1b5ce00e562fdf2b536e7310b435dfdb8888750.

Blocked by https://github.com/Kotlin/kotlinx.coroutines/issues/3673

### CODE REVIEW

**Review by veyndan — APPROVED** [review]

**Comment by JakeWharton** [comment]
But CI passed. I'm not aware of any usage of that utility in this repo.

**Comment by swankjesse** [comment]
The binary-incompatible change in coroutines breaks downstream consumers of Redwood. I’d like to make it easy and safe for downstreams to upgrade Redwood while we wait for a patch release on coroutines.

**Comment by swankjesse** [comment]
(In general I’d strongly prefer to not build Redwood on coroutines 1.7.0 and deploy it on 1.6.4.)

**Comment by JakeWharton** [comment]
Numerous other libraries have already been migrated (Turbine, Molecule, SQLDelight).

I would prefer to put a binary-compatible function into the coroutines test package in the internal repo to restore compatibility rather than whack-a-mole-ing all of our open source projects.

**Comment by swankjesse** [comment]
Works for me.

**Pull request closed without merging**
