### PR TITLE
Add unit tests for OnBackPressedDispatcher

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by swankjesse** [comment]
# ⚠️ stacked PR!

**Comment by swankjesse** [comment]
Part of https://github.com/cashapp/redwood/issues/1458

**Review by veyndan — APPROVED** [review]

**Review by JakeWharton — APPROVED** [review]
Are we testing real codepaths here? There's a lot of fake infrastructure in play and it's hard to understand what real behavior we're trying to test.

**Comment by swankjesse** [comment]
The `TreehouseAppContent` is the real codepath this is exercising. It’s at the center of 3 different lifecycles (view attach, code load, content), and so it’s been very scary to change. With this I’m hoping to make it a little bit better.

I also see some options to promote other things to be under test, perhaps by moving the boundaries of what’s an interface and what’s not.

**Comment by JakeWharton** [comment]
It's probably easier to see in the IDE where I can click around more easily. It's hard to see exact boundaries in the diff.

**Pull request merged**
