### PR TITLE
Add Width and Height modifiers for controlling the size of a widget.

### LINKED ISSUE #855: Width and Height configuration for children of Rows and Columns
### Problem Statement

I’ve got a column where I’d like to configure the minimum size of a child element. Perhaps something like this:

```
  @Composable
  Column {
    ...
    Button(
      layoutModifier = LayoutModifier
        .horizontalAlignment(CrossAxisAlignment.Stretch)
        .minHeight(40),
      text = theButtonLabel,
      ...
    )
  }
```

For this occurrence I think I want to specify a _minimum_ height, because if the row’s contents exceed that height (perhaps due to a long label text-wrapping), I’m happy with the element being taller than that size.

In another part of my layout I’d like to specify an element’s exact width=0 with `grow(1.0)` so that I can achieve 50/50 balance for adjacent elements:

```
  @Composable
  Row {
    Button(
      layoutModifier = LayoutModifier
        .horizontalAlignment(CrossAxisAlignment.Stretch)
        .width(0)
        .grow(1.0),
      text = "LEFT",
    )
    Button(
      layoutModifier = LayoutModifier
        .horizontalAlignment(CrossAxisAlignment.Stretch)
        .width(0)
        .grow(1.0),
      text = "RIGHT",
    )
  }
```

Without locking the width in at 0, the side-by-side elements only balance if their contents are the exact same width.

### Syntax

I’d like to express these layout goals in the API. The above syntax is illustrative; I’m not at all attached to it. Borrowing terms from HTML or iOS or Android would be ideal.

### Margin, Padding, Size

We have to decide if width and height includes padding or not. My preference is we follow [the standard CSS Box Model](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model#the_standard_css_box_model) and not include padding in width or height.

I’d also like for us to rename `Padding` to `Margin`, if that’s closer to its behavior. In particular, if an element doesn’t paint its background in the padding area we should probably rename it to margin.

### PR DESCRIPTION
**Pull request by colinrtwhite**
Adds modifiers to force specific width and/or height values for children of `Row`/`Column`. Example:

```kotlin
Row {
    Image(
        url = url,
        modifier = Modifier.size(20.dp, 20.dp),
    )
    Text("Some text")
}
```

~Open question: should we also add a `Size` modifier that sets both dimensions at once?~

Resolves: https://github.com/cashapp/redwood/issues/855

### CODE REVIEW

**Comment by JakeWharton** [comment]
> Open question: should we also add a Size modifier that sets both dimensions at once?

Compose UI has one. Looks like they all bottom out in a size element. We could just have a size function that combines the two.

**Review by JakeWharton — APPROVED** [review]
What's up with the two blank screenshots?

**Comment by colinrtwhite** [comment]
Hmm seems like a bug. Will take a look today.

Also I'll add a `size` function that combines the two modifiers.

**Review by veyndan — APPROVED** [review]
🎉 

We should also implement this in `LazyList`. I can do that in a follow-up.

**Comment by colinrtwhite** [comment]
Unfortunately we can't add scoped modifier extensions without context receivers as they require two receivers: `RowScope`/`ColumnScope` and `Modifier`. I'm going to add a `Size` modifier to the schema instead.

**Comment by colinrtwhite** [comment]
The Compose UI issue was caused by `placeable` not being set. This is because the measure callback is skipped if both width and height are fixed.

**Pull request merged**
